package datastructure;

public class MutableDouble {

	private double value_;

	public int eclipseAutoGeneratedHashCode() {
		final int prime = 31;
		int result = 1;
		long temp;
		temp = Double.doubleToLongBits(value_);
		result = prime * result + (int) (temp ^ (temp >>> 32));
		return result;
	}
	
	@Override
	//https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/src-html/org/apache/commons/lang/mutable/MutableDouble.html#line.280
	public int hashCode() {
		long bits = Double.doubleToLongBits(value_);
		return (int) (bits ^ (bits >>> 32));
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MutableDouble other = (MutableDouble) obj;
		if (Double.doubleToLongBits(value_) != Double.doubleToLongBits(other.value_))
			return false;
		return true;
	}

	public Double doubleValue() {
		return value_;
	}

	public MutableDouble(Double num){
		value_ = num ;
	}
	
}
